mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
routing-mark: 7894
allow-lan: true
ipv6: true
mode: rule
unified-delay: true
tcp-concurrent: true
find-process-mode: off
log-level: info
geodata-loader: standard
external-controller: :9999
disable-keep-alive: false
profile:
  store-selected: true
proxy-groups:
  - name: 选择节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Proxy.png
    type: select
    proxies:
      - 故障转移
      - 落地节点
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 低倍率节点
      - 手动选择
      - DIRECT
  - name: 手动选择
    icon: https://cdn.jsdelivr.net/gh/shindgewongxj/WHATSINStash@master/icon/select.png
    include-all: true
    type: select
  - name: 前置代理
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Area.png
    type: select
    include-all: true
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地
    proxies:
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 低倍率节点
      - 手动选择
      - DIRECT
  - name: 落地节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Airport.png
    type: select
    include-all: true
    filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地
  - name: 故障转移
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Bypass.png
    type: fallback
    url: https://cp.cloudflare.com/generate_204
    proxies:
      - 落地节点
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 低倍率节点
      - 手动选择
      - DIRECT
    interval: 180
    tolerance: 20
    lazy: false
  - name: 静态资源
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Cloudflare.png
    type: select
    proxies: &a1
      - 选择节点
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
      - 低倍率节点
      - 手动选择
      - 直连
  - name: AI
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/chatgpt.png
    type: select
    proxies: *a1
  - name: Telegram
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Telegram.png
    type: select
    proxies: *a1
  - name: YouTube
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/YouTube.png
    type: select
    proxies: *a1
  - name: Bilibili
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/bilibili.png
    type: select
    proxies:
      - 直连
      - 台湾节点
      - 香港节点
  - name: Netflix
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Netflix.png
    type: select
    proxies: *a1
  - name: Spotify
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Spotify.png
    type: select
    proxies: *a1
  - name: TikTok
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/TikTok.png
    type: select
    proxies: *a1
  - name: E-Hentai
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Ehentai.png
    type: select
    proxies: *a1
  - name: PikPak
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/PikPak.png
    type: select
    proxies: *a1
  - name: Truth Social
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/TruthSocial.png
    type: select
    proxies:
      - 美国节点
      - 选择节点
      - 手动选择
  - name: Bahamut
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Bahamut.png
    type: select
    proxies:
      - 台湾节点
      - 选择节点
      - 手动选择
      - 直连
  - name: Crypto
    icon: https://cdn.jsdmirror.com/gh/Koolson/Qure@master/IconSet/Color/Cryptocurrency_3.png
    type: select
    proxies: *a1
  - name: SSH(22端口)
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Server.png
    type: select
    proxies: *a1
  - name: 搜狗输入法
    icon: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/icons/Sougou.png
    type: select
    proxies:
      - 直连
      - REJECT
  - name: 直连
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Direct.png
    type: select
    proxies:
      - DIRECT
      - 选择节点
  - name: 广告拦截
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/AdBlack.png
    type: select
    proxies:
      - REJECT
      - 直连
  - name: 低倍率节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Lab.png
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    include-all: true
    filter: (?i)0.[0-5]|低倍率|省流|大流量|实验性
  - name: 香港节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hong_Kong.png
    include-all: true
    filter: (?i)香港|港|HK|hk|Hong Kong|HongKong|hongkong|🇭🇰
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 台湾节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Taiwan.png
    include-all: true
    filter: (?i)台|新北|彰化|TW|Taiwan|🇹🇼
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 新加坡节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Singapore.png
    include-all: true
    filter: (?i)新加坡|坡|狮城|SG|Singapore|🇸🇬
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 日本节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Japan.png
    include-all: true
    filter: (?i)日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan|🇯🇵
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: 美国节点
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/United_States.png
    include-all: true
    filter: (?i)美国|美|US|United States|🇺🇸
    exclude-filter: (?i)家宽|家庭|家庭宽带|商宽|商业宽带|星链|Starlink|落地|0.[0-5]|低倍率|省流|大流量|实验性
    type: url-test
    url: https://cp.cloudflare.com/generate_204
    interval: 60
    tolerance: 20
    lazy: false
  - name: GLOBAL
    icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Global.png
    include-all: true
    proxies:
      - 选择节点
      - 手动选择
      - 前置代理
      - 落地节点
      - 故障转移
      - 静态资源
      - AI
      - Telegram
      - YouTube
      - Bilibili
      - Netflix
      - Spotify
      - TikTok
      - E-Hentai
      - PikPak
      - Truth Social
      - Bahamut
      - Crypto
      - SSH(22端口)
      - 搜狗输入法
      - 直连
      - 广告拦截
      - 低倍率节点
      - 香港节点
      - 台湾节点
      - 新加坡节点
      - 日本节点
      - 美国节点
rule-providers:
  ADBlock:
    type: http
    behavior: domain
    format: mrs
    interval: 86400
    url: https://adrules.top/adrules-mihomo.mrs
    path: ./ruleset/ADBlock.mrs
  TruthSocial:
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/TruthSocial.list
    path: ./ruleset/TruthSocial.list
    behavior: classical
    interval: 86400
    format: text
    type: http
  SogouInput:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/sogouinput.txt
    path: ./ruleset/SogouInput.txt
  StaticResources:
    type: http
    behavior: domain
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./ruleset/StaticResources.txt
  CDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./ruleset/CDNResources.txt
  AI:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./ruleset/AI.txt
  TikTok:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/TikTok.list
    path: ./ruleset/TikTok.list
  EHentai:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/EHentai.list
    path: ./ruleset/EHentai.list
  SteamFix:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/SteamFix.list
    path: ./ruleset/SteamFix.list
  GoogleFCM:
    type: http
    behavior: classical
    interval: 86400
    format: text
    path: ./ruleset/FirebaseCloudMessaging.list
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list
  AdditionalFilter:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalFilter.list
    path: ./ruleset/AdditionalFilter.list
  AdditionalCDNResources:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/AdditionalCDNResources.list
    path: ./ruleset/AdditionalCDNResources.list
  Crypto:
    type: http
    behavior: classical
    format: text
    interval: 86400
    url: https://cdn.jsdelivr.net/gh/powerfullz/override-rules@master/ruleset/Crypto.list
    path: ./ruleset/Crypto.list
rules:
  - RULE-SET,ADBlock,广告拦截
  - RULE-SET,AdditionalFilter,广告拦截
  - RULE-SET,SogouInput,搜狗输入法
  - RULE-SET,TruthSocial,Truth Social
  - RULE-SET,StaticResources,静态资源
  - RULE-SET,CDNResources,静态资源
  - RULE-SET,AdditionalCDNResources,静态资源
  - RULE-SET,AI,AI
  - RULE-SET,Crypto,Crypto
  - RULE-SET,EHentai,E-Hentai
  - RULE-SET,TikTok,TikTok
  - RULE-SET,SteamFix,直连
  - RULE-SET,GoogleFCM,直连
  - GEOSITE,GOOGLE-PLAY@CN,直连
  - GEOSITE,TELEGRAM,Telegram
  - GEOSITE,YOUTUBE,YouTube
  - GEOSITE,NETFLIX,Netflix
  - GEOSITE,SPOTIFY,Spotify
  - GEOSITE,BAHAMUT,Bahamut
  - GEOSITE,BILIBILI,Bilibili
  - GEOSITE,MICROSOFT@CN,直连
  - GEOSITE,PIKPAK,PikPak
  - GEOSITE,GFW,选择节点
  - GEOSITE,CN,直连
  - GEOSITE,PRIVATE,直连
  - GEOIP,NETFLIX,Netflix,no-resolve
  - GEOIP,TELEGRAM,Telegram,no-resolve
  - GEOIP,CN,直连
  - GEOIP,PRIVATE,直连
  - DST-PORT,22,SSH(22端口)
  - MATCH,选择节点
sniffer:
  sniff:
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080
        - 8880
    QUIC:
      ports:
        - 443
        - 8443
  override-destination: false
  enable: true
  force-dns-mapping: true
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.push.apple.com
dns:
  enable: true
  ipv6: true
  prefer-h3: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - geosite:private
    - geosite:connectivity-check
    - geosite:cn
    - Mijia Cloud
    - dig.io.mi.com
    - localhost.ptlogin2.qq.com
    - "*.icloud.com"
    - "*.stun.*.*"
    - "*.stun.*.*.*"
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - system
    - 223.5.5.5
    - 119.29.29.29
    - 180.184.1.1
  fallback:
    - quic://dns0.eu
    - https://dns.cloudflare.com/dns-query
    - https://dns.sb/dns-query
    - tcp://208.67.222.222
    - tcp://8.26.56.2
  proxy-server-nameserver:
    - quic://223.5.5.5
    - tls://dot.pub
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
  asn: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb

