name: Generate YAML Configs and Sync To Forgejo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-and-generate:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install --no-audit --no-fund

      - name: Generate YAML files
        run: npm run generate

      - name: Commit and push YAML changes
        run: |
          if [ ! -d "yamls" ]; then
            echo "yamls directory missing"
            exit 1
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add yamls
          git commit -m "chore(ci): auto-generate yamls" || echo "Nothing to commit"
          git push
      - name: Push to Forgejo Mirror
        env:
          FORGEJO_PAT: ${{ secrets.FORGEJO_PAT }}
          FORGEJO_REPO_URL: ${{ secrets.FORGEJO_REPO_URL }}
        run: |
          echo "Syncing to Forgejo..."

          # 格式: https://<token>@your-forgejo-domain.com/user/repo.git
          SYNC_URL=$(echo "$FORGEJO_REPO_URL" | sed "s|://|://$FORGEJO_PAT@|")
          
          git push --mirror "$SYNC_URL"
          echo "Sync completed."